DMofaUniversity/DMofaUniversity/Controllers/ManageResultController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;
using DMofaUniversity.DataAccessLayer;
using DMofaUniversity.Models;
using WebGrease.Css.Ast.Selectors;

namespace DMofaUniversity.Controllers
{
    public class ManageResultController : Controller
    {
        //
        // GET: /ManageResult/
        public ActionResult GetResultSheet()
        {
            
            List<tblSemester> listofSemesters=new List<tblSemester>();
            List<tblSesson> listofSesson=new List<tblSesson>();
            using (DeptMofaUniversityConn db=new DeptMofaUniversityConn())
            {
                listofSemesters = db.tblSemesters.ToList();
                listofSesson = db.tblSessons.ToList();
            }
            ViewBag.SemesterList = listofSemesters;
            ViewBag.Sesson = listofSesson;
            return View();
        }
        [HttpPost]
        public ActionResult GetResultSheet(SemesterCourse semesterCourse)
        {
            List<tblSemester> listofSemesters = new List<tblSemester>();
            List<tblSesson> listofSesson = new List<tblSesson>();
            using (DeptMofaUniversityConn db = new DeptMofaUniversityConn())
            {
                listofSemesters = db.tblSemesters.ToList();
                listofSesson = db.tblSessons.ToList();
            }
            ViewBag.SemesterList = listofSemesters;
            ViewBag.Sesson = listofSesson;

            StudentOfaSemesterGateway studentOfaSemesterGateway=new StudentOfaSemesterGateway();
            List<tblStudent> studentlist=new List<tblStudent>();
            studentlist = studentOfaSemesterGateway.GetStudentOfaSemester(semesterCourse);
            DeptMofaUniversityConn database=new DeptMofaUniversityConn();
            DataTable dt = new DataTable("Grid");
                    dt.Columns.AddRange(new DataColumn[5]
                { 
                    new DataColumn("StudentID"),
                    new DataColumn("CID"),
                    new DataColumn("FirstMidMark"),
                    new DataColumn("SecondtMidMark"),
                    new DataColumn("Roll"),
             
                });
                var midResults = from midResult in database.tblMidResults
                                     select midResult;
                foreach (var midResult in midResults)
                {
                    dt.Rows.Add(midResult.);
                }
             using (XLWorkbook wb = new XLWorkbook())
            {
                wb.Worksheets.Add(dt);
                using (MemoryStream stream = new MemoryStream())
                {
                    wb.SaveAs(stream);
                    return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Grid.xlsx");
                }
             }


            return View();
        }
        public JsonResult GetCousreBySemesterId(int SemesterId)
        {   
            string conString = WebConfigurationManager.ConnectionStrings["commonCon"].ToString();
            List<tblCourse>courseList=new List<tblCourse>();
            using (SqlConnection conn=new SqlConnection(conString))
            {
                SqlCommand com = new SqlCommand("select tblCourse.CID,tblCourse.Course_Title from  tblCourse inner join tblTeacherCourseAssign on tblCourse.CID=tblTeacherCourseAssign.CID" +
                                                " where tblTeacherCourseAssign.TeacherEmail='" + (string)Session["Email"] + "' and tblCourse.SID='" + SemesterId + "'", conn);
                conn.Open();
                SqlDataReader reader = com.ExecuteReader();
                if (reader.HasRows)
                {

                    while (reader.Read())
                    {
                        tblCourse course=new tblCourse();
                        course.CID = Convert.ToInt16(reader[0]);
                        course.Course_Title = reader[1].ToString();
                        courseList.Add(course);
                    }
                    reader.Close();
                }
            }
            return Json(courseList, JsonRequestBehavior.AllowGet);
        }



	}
}

DMofaUniversity/DMofaUniversity/Views/ManageResult/GetResultSheet.cshtml
@using DMofaUniversity.Models
@model DMofaUniversity.Models.SemesterCourse

@{
    ViewBag.Title = "GetResultSheet";
    if ((string)Session["Email"] == null)
    {
        Response.Redirect(Url.Action("ManageLogIn", "ManageRegistration"));
    }
}

<h2>Get Result Sheet</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    <div style="background-color: bisque">
        <div class="form-horizontal">
            <h4>Get a Excel Sheet with student Roll of a Semester</h4>
            <hr />
            @Html.ValidationSummary(true)

            <div class="form-group">
                @Html.LabelFor(model => model.SemesterId, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @*@Html.EditorFor(model => model.SemesterId)
                    @Html.ValidationMessageFor(model => model.SemesterId)*@
                    <select name="SemesterId" id="SemesterId">
                        <option value="">-----Select a Semester-----</option>
                        @foreach (tblSemester semester in ViewBag.SemesterList)
                        {
                            <option value="@semester.SID">@semester.Semester</option>
                        }
                    </select>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CourseId, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @*@Html.EditorFor(model => model.CourseId)
                    @Html.ValidationMessageFor(model => model.CourseId)*@
                    <select name="CourseId" id="CourseId"></select>
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.SessonId, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @*@Html.EditorFor(model => model.SessonId)
                      @Html.ValidationMessageFor(model => model.SessonId)*@
                    <select name="SessonId" id="SessonId">
                        <option value="">-----Select a Sesson-----</option>
                        @foreach (tblSesson sesson in ViewBag.Sesson)
                        {
                            <option value="@sesson.SessonID">@sesson.Sesson</option>
                        }
                    </select>
                </div>
            </div>
            

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Make Excel" class="btn btn-info" />
                </div>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Do more", "GetResultSheet")
</div>
@section scripts
{
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script>
        $(document).ready(function () {

            $("#SemesterId").change(function () {

                var deptId = $("#SemesterId").val();
                $("#CourseId").empty();
                var json = {
                    SemesterId: deptId
                };

                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetCousreBySemesterId", "ManageResult")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(json),
                    success: function (data) {
                        //alert(data);
                        $.each(data, function (key, value) {
                            //alert(key);
                            $("#CourseId").append('<option value=' + value.CID + '>' + value.Course_Title + '</option>');

                        });
                    }
                });
            });
        });

    </script>
}