DMofaUniversity/DMofaUniversity/Controllers/ManageTeacheController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DMofaUniversity.Models;

namespace DMofaUniversity.Controllers
{
    public class ManageTeacheController : Controller
    {
        //
        // GET: /ManageTeache/
        public ActionResult SaveTeache()
        {
            return View();
        }
        [HttpPost]
        public ActionResult SaveTeache(tblTeacher tblTeacher)
        {
            int sign = 0;
            string message = "";
            string fileName = Path.GetFileNameWithoutExtension(tblTeacher.ImageFile.FileName);
            string extention = Path.GetExtension(tblTeacher.ImageFile.FileName);
            fileName = fileName + DateTime.Now.ToString("yymmssfff") + extention;
            tblTeacher.TeacherImagePath = "~/Images/" + fileName;
            fileName = Path.Combine(Server.MapPath("~/Images/"), fileName);
            tblTeacher.ImageFile.SaveAs(fileName);
            using (DeptMofaUniversityConn db=new DeptMofaUniversityConn())
            {
                db.tblTeachers.Add(tblTeacher);
                db.SaveChanges();
                sign = sign + 1;

            }
            ModelState.Clear();
            if (sign > 0)
            {
                message = tblTeacher.Name + " is added as teacher";
            }
            TempData["message"] = message;
            return View();
         }
        
        public ActionResult ShowTeache(tblTeacher tblTeacher)
        { 
            Models.tblTeacher teacher=new tblTeacher();
            using (DeptMofaUniversityConn db = new DeptMofaUniversityConn())
            {
                teacher = db.tblTeachers.FirstOrDefault(m => m.Email == tblTeacher.Email);
            }
            
            ViewBag.ateacher = teacher;
            return View();
        }
	}
}

DMofaUniversity/DMofaUniversity/Views/ManageTeache/SaveTeache.cshtml
@model DMofaUniversity.Models.tblTeacher

@{
    ViewBag.Title = "SaveTeache";
}

<h2>Save Teacher</h2>


@using (Html.BeginForm("SaveTeache","ManageTeache",FormMethod.Post,new{enctype="multipart/form-data"})) 
{
    @Html.AntiForgeryToken()
    <div style="background-color: bisque ">
        <div class="form-horizontal">
            <h4></h4>
            <hr />
            @Html.ValidationSummary(true)

            @*<div class="form-group">
                    @Html.LabelFor(model => model.TeacherID, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.TeacherID)
                        @Html.ValidationMessageFor(model => model.TeacherID)
                    </div>
                </div>*@

            <div class="form-group">
                @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name)
                    @Html.ValidationMessageFor(model => model.Name)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.TeacherImagePath, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @*@Html.EditorFor(model => model.TeacherImagePath)*@
                    <input type="file" name="ImageFile" required />
                    @Html.ValidationMessageFor(model => model.TeacherImagePath)
                   
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Deparment, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Deparment)
                    @Html.ValidationMessageFor(model => model.Deparment)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.F_Name, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.F_Name)
                    @Html.ValidationMessageFor(model => model.F_Name)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.M_Name, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.M_Name)
                    @Html.ValidationMessageFor(model => model.M_Name)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.BirthDate, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @*@Html.EditorFor(model => model.BirthDate)*@
                    <input type="date" name="BirthDate"required />
                    @Html.ValidationMessageFor(model => model.BirthDate)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.NationalID, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NationalID)
                    @Html.ValidationMessageFor(model => model.NationalID)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Age, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Age)
                    @Html.ValidationMessageFor(model => model.Age)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Religion, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Religion)
                    @Html.ValidationMessageFor(model => model.Religion)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Caste, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Caste)
                    @Html.ValidationMessageFor(model => model.Caste)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Nationality, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Nationality)
                    @Html.ValidationMessageFor(model => model.Nationality)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Mobile, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Mobile)
                    @Html.ValidationMessageFor(model => model.Mobile)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.BSc_Result, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.BSc_Result)
                    @Html.ValidationMessageFor(model => model.BSc_Result)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.BSc_Univarsity, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.BSc_Univarsity)
                    @Html.ValidationMessageFor(model => model.BSc_Univarsity)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.MSc_Result, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.MSc_Result)
                    @Html.ValidationMessageFor(model => model.MSc_Result)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.MSc_Univarsity, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.MSc_Univarsity)
                    @Html.ValidationMessageFor(model => model.MSc_Univarsity)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email)
                    @Html.ValidationMessageFor(model => model.Email)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Division, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Division)
                    @Html.ValidationMessageFor(model => model.Division)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Distric, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Distric)
                    @Html.ValidationMessageFor(model => model.Distric)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Thana, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Thana)
                    @Html.ValidationMessageFor(model => model.Thana)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Post_Office, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Post_Office)
                    @Html.ValidationMessageFor(model => model.Post_Office)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Post_Code, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Post_Code)
                    @Html.ValidationMessageFor(model => model.Post_Code)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Present_Address, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Present_Address)
                    @Html.ValidationMessageFor(model => model.Present_Address)
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save Teacher" class="btn btn-info" />
                </div>
            </div>
        </div>
    </div>
}
@if (TempData["message"] != null)
{
    <script type="text/javascript">
        alert("@TempData["message"]");
    </script>
}
<div>
    @Html.ActionLink("Do more", "SaveTeache")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DMofaUniversity/DMofaUniversity/Views/ManageTeache/ShowTeache.cshtml
@model DMofaUniversity.Models.tblTeacher

@{
    ViewBag.Title = "ShowTeache";
}

<h2>Teacher's information</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    <div style="background-color: bisque">
        <div class="form-horizontal">
            <h4>Search with email</h4>
            <hr />
            @Html.ValidationSummary(true)

            @*<div class="form-group">
                    @Html.LabelFor(model => model.TeacherID, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.TeacherID)
                        @Html.ValidationMessageFor(model => model.TeacherID)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name)
                        @Html.ValidationMessageFor(model => model.Name)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.TeacherImagePath, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.TeacherImagePath)
                        @Html.ValidationMessageFor(model => model.TeacherImagePath)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Deparment, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Deparment)
                        @Html.ValidationMessageFor(model => model.Deparment)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.F_Name, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.F_Name)
                        @Html.ValidationMessageFor(model => model.F_Name)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.M_Name, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.M_Name)
                        @Html.ValidationMessageFor(model => model.M_Name)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.BirthDate, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.BirthDate)
                        @Html.ValidationMessageFor(model => model.BirthDate)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.NationalID, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.NationalID)
                        @Html.ValidationMessageFor(model => model.NationalID)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Age, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Age)
                        @Html.ValidationMessageFor(model => model.Age)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Religion, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Religion)
                        @Html.ValidationMessageFor(model => model.Religion)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Caste, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Caste)
                        @Html.ValidationMessageFor(model => model.Caste)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Nationality, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Nationality)
                        @Html.ValidationMessageFor(model => model.Nationality)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Mobile, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Mobile)
                        @Html.ValidationMessageFor(model => model.Mobile)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.BSc_Result, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.BSc_Result)
                        @Html.ValidationMessageFor(model => model.BSc_Result)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.BSc_Univarsity, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.BSc_Univarsity)
                        @Html.ValidationMessageFor(model => model.BSc_Univarsity)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.MSc_Result, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.MSc_Result)
                        @Html.ValidationMessageFor(model => model.MSc_Result)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.MSc_Univarsity, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.MSc_Univarsity)
                        @Html.ValidationMessageFor(model => model.MSc_Univarsity)
                    </div>
                </div>*@

            <div class="form-group">
                @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email)
                    @Html.ValidationMessageFor(model => model.Email)
                </div>
            </div>

            @*<div class="form-group">
                    @Html.LabelFor(model => model.Division, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Division)
                        @Html.ValidationMessageFor(model => model.Division)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Distric, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Distric)
                        @Html.ValidationMessageFor(model => model.Distric)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Thana, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Thana)
                        @Html.ValidationMessageFor(model => model.Thana)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Post_Office, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Post_Office)
                        @Html.ValidationMessageFor(model => model.Post_Office)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Post_Code, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Post_Code)
                        @Html.ValidationMessageFor(model => model.Post_Code)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Present_Address, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Present_Address)
                        @Html.ValidationMessageFor(model => model.Present_Address)
                    </div>
                </div>*@

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Search Teacher" class="btn btn-info" />
                </div>
            </div>
        </div>
    </div>
}
@if (IsPost)
{
    if (ViewBag.ateacher==null)
    {
        <script type="text/javascript">
            alert(" this email is not matched ")
        </script>
    }
    else
    {
      <div style="background-color: bisque">
    <h4>Teacher's Details</h4>
	<hr />
    <dl class="dl-horizontal">
        @*<dt>
            @Html.DisplayNameFor(model => model.TeacherID)
        </dt>

        <dd>
            @ViewBag.ateacher.TeacherID
        </dd>*@

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @ViewBag.ateacher.Name
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TeacherImagePath)
        </dt>

        <dd>
           <img src="@Url.Content(ViewBag.ateacher.TeacherImagePath)"height="150" width="150"/>
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Deparment)
        </dt>

        <dd>
            @ViewBag.ateacher.Deparment
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.F_Name)
        </dt>

        <dd>
            @ViewBag.ateacher.F_Name
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.M_Name)
        </dt>

        <dd>
            @ViewBag.ateacher.M_Name
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>

        <dd>
            @ViewBag.ateacher.BirthDate
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NationalID)
        </dt>

        <dd>
            @ViewBag.ateacher.NationalID
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Age)
        </dt>

        <dd>
            @ViewBag.ateacher.Age
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Religion)
        </dt>

        <dd>
            @ViewBag.ateacher.Religion
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Caste)
        </dt>

        <dd>
            @ViewBag.ateacher.Caste
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nationality)
        </dt>

        <dd>
            @ViewBag.ateacher.Nationality
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Mobile)
        </dt>

        <dd>
            @ViewBag.ateacher.Mobile
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BSc_Result)
        </dt>

        <dd>
            @ViewBag.ateacher.BSc_Result
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BSc_Univarsity)
        </dt>

        <dd>
            @ViewBag.ateacher.BSc_Univarsity
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MSc_Result)
        </dt>

        <dd>
            @ViewBag.ateacher.MSc_Result
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MSc_Univarsity)
        </dt>

        <dd>
            @ViewBag.ateacher.MSc_Univarsity
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @ViewBag.ateacher.Email
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Division)
        </dt>

        <dd>
            @ViewBag.ateacher.Division
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Distric)
        </dt>

        <dd>
            @ViewBag.ateacher.Distric
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Thana)
        </dt>

        <dd>
            @ViewBag.ateacher.Thana
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Post_Office)
        </dt>

        <dd>
            @ViewBag.ateacher.Post_Office
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Post_Code)
        </dt>

        <dd>
            @ViewBag.ateacher.Post_Code
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Present_Address)
        </dt>

        <dd>
            @ViewBag.ateacher.Present_Address
        </dd>

    </dl>
</div>
    }
    
}
<div>
    @Html.ActionLink("Do more", "ShowTeache")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}