DMofaUniversity/DMofaUniversity/Controllers/ManageCourseTeacherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DMofaUniversity.Models;

namespace DMofaUniversity.Controllers
{
    public class ManageCourseTeacherController : Controller
    {
        //
        // GET: /ManageCourseTeacher/
        public ActionResult SaveCourseToTeacher()
        {
            List<tblSemester> listOfSemester = new List<tblSemester>();
            List<tblTeacher> listOfteacher = new List<tblTeacher>();
            using (DeptMofaUniversityConn db = new DeptMofaUniversityConn())
            {
                listOfSemester = db.tblSemesters.ToList();
                listOfteacher = db.tblTeachers.ToList();
            }
            ViewBag.semesters = listOfSemester;
            ViewBag.teachers = listOfteacher;
            return View();
        }
        [HttpPost]
        public ActionResult SaveCourseToTeacher(tblTeacherCourseAssign courseAssign)
        {
            string message = "";
            int sign = 0;
            List<tblSemester> listOfSemester = new List<tblSemester>();
            List<tblTeacher> listOfteacher = new List<tblTeacher>();
            using (DeptMofaUniversityConn db = new DeptMofaUniversityConn())
            {
                listOfSemester = db.tblSemesters.ToList();
                listOfteacher = db.tblTeachers.ToList();
            }
            ViewBag.semesters = listOfSemester;
            ViewBag.teachers = listOfteacher;
            string email = "";
            tblTeacher teacher=new tblTeacher();
            using (DeptMofaUniversityConn db=new DeptMofaUniversityConn())
            {
                teacher = db.tblTeachers.FirstOrDefault(m => m.TeacherID == courseAssign.TeacherId);
            }
            courseAssign.TeacherEmail = teacher.Email;
            using (CourseAssignConn db=new CourseAssignConn())
            {
                db.tblTeacherCourseAssigns.Add(courseAssign);
                db.SaveChanges();
                sign = sign + 1;
            }
            tblCourse course=new tblCourse();
            using (DeptMofaUniversityConn db=new DeptMofaUniversityConn())
            {
                course = db.tblCourses.FirstOrDefault(m => m.CID == courseAssign.CID);
            }
            if (sign>0)
            {
                message = course.Course_Title + " is assigned to " + teacher.Name;
            }
            TempData["m"] = message;
            return View();
        }
        public JsonResult GetCousreBySemesterId(int Semesterid)
        { 
            List<tblCourse>courseList=new List<tblCourse>();
            using (DeptMofaUniversityConn db=new DeptMofaUniversityConn())
            {
                courseList = db.tblCourses.Where(m=>m.SID==Semesterid).ToList();
            }
            return Json(courseList, JsonRequestBehavior.AllowGet);
        }
	}
}

DMofaUniversity/DMofaUniversity/Views/ManageCourseTeacher/SaveCourseToTeacher.cshtml
@using DMofaUniversity.Models
@model DMofaUniversity.Models.tblTeacherCourseAssign

@{
    ViewBag.Title = "SaveCourseToTeacher";
}

<h2>Assigne Course To Teacher</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    <div style="background-color: bisque">
        <div class="form-horizontal">
            <h4></h4>
            <hr />
            @Html.ValidationSummary(true)

            @*<div class="form-group">
                @Html.LabelFor(model => model.tblTeacherCourseID, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.tblTeacherCourseID)
                    @Html.ValidationMessageFor(model => model.tblTeacherCourseID)
                </div>
            </div>*@

            <div class="form-group">
                @Html.LabelFor(model => model.SID, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @*@Html.EditorFor(model => model.SID)
                    @Html.ValidationMessageFor(model => model.SID)*@
                    <select name="SID" id="semesterid">
                        <option value="">---Select a Semester----</option>
                        @foreach (tblSemester semester in ViewBag.semesters)
                        {
                            <option value="@semester.SID">@semester.Semester</option>
                        }
                    </select>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CID, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @*@Html.EditorFor(model => model.CID)
                    @Html.ValidationMessageFor(model => model.CID)*@
                    <select name="CID" id="Courseid"></select>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.TeacherId, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @*@Html.EditorFor(model => model.TeacherId)
                    @Html.ValidationMessageFor(model => model.TeacherId)*@
                    <select name="TeacherId">
                        <option value="">-----Select a Teacher----</option>
                        @foreach (tblTeacher teacher in ViewBag.teachers)
                        {
                            <option value="@teacher.TeacherID">@teacher.Name</option>
                        }
                    </select>
                </div>
            </div>

            @*<div class="form-group">
                @Html.LabelFor(model => model.TeacherEmail, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TeacherEmail)
                    @Html.ValidationMessageFor(model => model.TeacherEmail)
                </div>
            </div>*@

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Assigne" class="btn btn-info" />
                </div>
            </div>
        </div>
    </div>
}
@if (TempData["m"] != null)
{
    <script type="text/javascript">
        alert("@TempData["m"]");
    </script>
}
<div>
    @Html.ActionLink("Do more", "SaveCourseToTeacher")
</div>
@section scripts
{
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script>
        $(document).ready(function () {

            $("#semesterid").change(function () {

                var deptId = $("#semesterid").val();
                $("#Courseid").empty();
                var json = {
                    semesterid: deptId
                };

                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetCousreBySemesterId", "ManageCourseTeacher")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(json),
                    success: function (data) {
                        //alert(data);
                        $.each(data, function (key, value) {
                            //alert(key);
                            $("#Courseid").append('<option value=' + value.CID + '>' + value.Course_Title + '</option>');

                        });
                    }
                });
            });
        });

    </script>
}